version: '3'

services:
### NGINX Server #########################################
  node:
    image: "node:8.17.0-buster-slim"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run start-docker"

### MySQL ################################################
  mysql:
    image: "mysql:8.0.18"
    environment:
      - MYSQL_DATABASE=hapi
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./:/var/www:cached
    ports:
      - "3306:3306"
